### ISSUE TITLE
Footer: medium screen display

### ISSUE THREAD

**Issue by Theo6890** [Theo6890/nuron-template#1]
The footer on smaller screen should be updated to look the same as on mobile

how should be:
<img width="590" alt="footer-current" src="https://user-images.githubusercontent.com/37904797/179356692-4451feb7-246b-4d71-a27b-6a22cb60927d.png">

how it is:
<img width="1717" alt="footer-goal" src="https://user-images.githubusercontent.com/37904797/179356703-dd607d55-caa4-4084-957d-1085810c239f.png">

**Comment by Theo6890** [comment]
- [ ] Put `Contact Us Terms Privacy Policy Support & FAQs` under all rights reserved
<img width="915" alt="Screenshot 2022-07-16 at 18 17 50" src="https://user-images.githubusercontent.com/37904797/179365377-958b9f81-8b75-4388-94ca-093d9f82269f.png">

**Comment by stechx1** [comment]
Just for smaller or medium screen or for larger screen as well?

**Comment by Theo6890** [comment]
only for medium screen
