### ISSUE TITLE
Assets and Components: unused code to delete

### ISSUE THREAD

**Issue by Theo6890** [Theo6890/nuron-template#10]
Assets:
- [x] Blog comments: _style.scss

Components:
- [x] `components/menu`: both `main-menu` & `mobile-menu` --> megamenu & submenu (keep into another branch)
- [x] `components/share-modal` folder
- [x] `components/product-details/bid-tab/bids-tab-content.jsx`
- [x] `components/top-seller` folder
Take out files of `layout-1` sub-folder as there are no alternative displays:
- [x] `components/product/layout-1/index.js`
- [x] `components/product-filter/layout-1/index.js`
- [x] `components/section-title/layout-1/index.js`
- [x] `components/product/layout-1/index.js`

**Comment by stechx1** [comment]
Blog comments: _style.scss
 
 I didn't get that.

**Comment by stechx1** [comment]
components/share-modal 

This is being used in author page. 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/109359174/179394902-4bfbcf9e-fa10-4b58-9419-10da8a8409b4.png">

**Comment by stechx1** [comment]
components/menu: both main-menu & mobile-menu --> megamenu & submenu (keep into another branch)
 
 Needs explanation as well

**Comment by Theo6890** [comment]
> components/share-modal
> 
> This is being used in author page. <img alt="image" width="740" src="https://user-images.githubusercontent.com/109359174/179394902-4bfbcf9e-fa10-4b58-9419-10da8a8409b4.png">

Okay so let's keep it 👌

**Comment by Theo6890** [comment]
> Blog comments: _style.scss
> 
> I didn't get that.

Delete the comments where Blog page is mentioned

**Comment by Theo6890** [comment]
> components/menu: both main-menu & mobile-menu --> megamenu & submenu (keep into another branch)
> 
> Needs explanation as well

I wanted to keep the code of these into another branch. Though, you can delete completely mega menu and submenu 😉
