### ISSUE TITLE
Utils: is absolutely all the code in the files there used somewhere?

### ISSUE THREAD

**Issue by Theo6890** [Theo6890/nuron-template#12]

**Comment by stechx1** [comment]
Yes, all code except two methods. GetMonth & flatDeep inside method.js file. Should I delete these two functions?

**Comment by stechx1** [comment]
Deleted these two methods. Everything else is required

**Comment by Theo6890** [comment]
8705019cf8b9347671b685e54fcaf35217f4f699 : `utils/methods.js`
