### ISSUE TITLE
Product details: delete highest bid info & move price next to buy

### ISSUE THREAD

**Issue by Theo6890** [Theo6890/nuron-template#4]
Current state to update:
<img width="915" alt="Screenshot 2022-07-16 at 14 13 26" src="https://user-images.githubusercontent.com/37904797/179356813-3266b8a9-f56d-4af1-a74a-76632ebc843f.png">

**Comment by Theo6890** [comment]
@stechx1 can you 

- [x] keep the background of the button and a large button?
- [x] put the price on the left of Buy & let quite some space between the amount & buy?

**Comment by Theo6890** [comment]
- [x] put the price in blue colour (the one used on explore page for the price)

**Comment by stechx1** [comment]
@Theo6890 keep the background of the button and a large button?
Large button I understood but what do you mean by keep the background? It means keep background color same?

**Comment by Theo6890** [comment]
by the  background I mean the black card around the button

**Comment by stechx1** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/109359174/179366881-0f603137-d1fd-4b6b-ae55-35fba1126fd4.png">

Is it okay now?

**Comment by Theo6890** [comment]
yes perfect
